# Site settings
title: dspaudio.github.io
email: dspaudio@gmail.com
description: dspaudio's Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dspaudio.github.io" # the base hostname & protocol for your site
github_username:  dspaudio
